//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskyJ.DataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryJTable : TaskyJ.Globals.Data.DataObjects.DBCategoryJ
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	public CategoryJTable()
    	{
    		this.TaskyJTables = new HashSet<TaskyJTable>();
    	}
    
    
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	public virtual ICollection<TaskyJTable> TaskyJTables { get; set; }
    }
}
