//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskyJ.DataRepo
{
	using Microsoft.EntityFrameworkCore;
	using System;
	
	public partial class TaskyJEntities : DbContext
	{
		public TaskyJEntities()
			//: base("name=TaskyJEntities")
		{
		}/*
	
		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}*/
	
		public virtual DbSet<TaskyJTable> TaskyJTable { get; set; }
		public virtual DbSet<CategoryJTable> CategoryJTable { get; set; }
	}
}
