#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskyJ.Interface.Android.Resource", IsApplication=true)]

namespace TaskyJ.Interface.Android
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F010000
			public const int CategoryLabel = 2130771968;
			
			// aapt resource value: 0x7F01000D
			public const int chkSpecifyDeadline = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int cmdAddNew = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int cmdCancel = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int cmdDelete = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int cmdEmptyTrash = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int cmdQuickAdd = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int cmdRefresh = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int cmdSave = 2130771988;
			
			// aapt resource value: 0x7F010001
			public const int CompletedLabel = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int CreationDate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int CreationDateLabel = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int Description = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int DescriptionLabel = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int ID = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int IDLabel = 2130771975;
			
			// aapt resource value: 0x7F010015
			public const int ivwCategory = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int menuDelete = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int menuFinish = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int menuRestore = 2130771992;
			
			// aapt resource value: 0x7F010008
			public const int Name = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int NameLabel = 2130771977;
			
			// aapt resource value: 0x7F010019
			public const int nbpCompleted = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int pckDate = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int pckTime = 2130771995;
			
			// aapt resource value: 0x7F01000A
			public const int PriorityLabel = 2130771978;
			
			// aapt resource value: 0x7F01001C
			public const int spnCategory = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int spnPriority = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int swtShowDeleted = 2130771998;
			
			// aapt resource value: 0x7F01000B
			public const int TaskListLabel = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int TaskListView = 2130771980;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int SingleTask = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int taskmenu = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
