//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskyJ.Globals.Data {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskyJ.Globals.Data.ImagesResource", typeof(ImagesResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADmsAAA5rAVT+DQYAAAUwSURBVGhD7ZlbbFRVFIbXmZlDO20p01JanEs7mV70AamIjiAoYIpACjEiF/XFIqkpGnwQEtAHWk0UY7kEEVtppahR1BiNkdJWiBbFGAoP8qRBatBe0qkJ4dILpZ2zXWvP6tRpezrT6UytZL5m56z177P37P9cV04hRowY/y3HMzNd1DiNGgbeRoVau/0Bo6ado0Yxy1EhakbqrdYCnPwUhqnUKCZNdkaBqBips9vXCoPhOIZJPkWSRBr1cR5RIm6k3mbbgJtj2OIoV9RpsjGkHauz2db70sih8DYi1Dsc24QQ5RjKeY0zLJBzsBoE/jVvLQbvtaskEwIUZfuqlpZ9nEvOnO3YrBiUFZz6ENC4yJ3xLme6ROyM1Nvtb6KJPRhKE+qsdMh7/xNI [rest of string was truncated]&quot;;.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADmsAAA5rAVT+DQYAAASwSURBVGhD7ZlraBxVGIbfs5ckm8tuklKqVgs2bRrT2DaGVIykKiqm4AVRi/6wILUgGANW6Q/FOk1K+6cGkVZREH+VgNgoRm2wpbUXi80NsZFYBAUVWkxSqW1Mspvd4zszJzWXvcxkZ3YD7gPfnO98M5s575nvnDNnghw5cvw/EKrMOPKcVgkvdrEFyyDRi1D5brG6ZVKdtk1WhMi+tgoI2Y/gHSHk3whc+wkY+7lb1Gub1SW28agys4joayiuCaG0AQjcCixtAgpuaJL9rY3qCttkR4hELfxLVEWHieErZzy2VgVs43pqyXtRjCieo1vJuw0ihqN4W+sEvOuRv4xFAIhcpv0FRKdasHPPIIXeQyukHRdn0G3+peS4KkRuwi1szDd0V5oRgxiq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string reminder {
            get {
                return ResourceManager.GetString("reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADmsAAA5rAVT+DQYAAAZaSURBVGhD7ZhrbBRVFMfPnZ3Z3XbLVkqhkLYoRBFMlA9QIakaIUYSBaIxRGJiH4gtMSZCaE2Qtkxp6QdaDF8IyqslCvjCCCqKMUA0qfKUBChKwqOtgdJSoWXpLjs7cz135267u53ddna3xcT9JbP3nDOzu/c/59w7dy4kSZLk/wHh7QPjHXlLWp/mfhUoPA+ETsfWhuEeQuA3qcNZvW1bqaJfGZ0HKISS4oqGEo1ALXYikwcDKHh6aVNt2dfcH5IHImTJki8sjsdbd+K/F/JQMKZFMATejipp09vqIojwAKWLzYpgjHpGiio/fBJAPYtm+E2MKRMBEiaEnvpYAtL5KHZyBnZoCg5aOw7eMdiqIJBraP8FYL1Y9I24hlCyin9tAApyU215NfdM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
    }
}
